--- # Configuration Port
server:
  port: 8080
  ssl:
    enabled: true
    key-store: "src/main/resources/keystore.p12"
    key-store-type: "PKCS12"
    key-store-password: "^ldcc2024"

--- # Configuration Thymeleaf
spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    cache: false

--- # Configuration Devtools
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

--- # Configuration MariaDb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot
    username: boot
    password: boot
    hikari:
      auto-commit: false

--- # Configuration mybatis
mybatis:
  mapper-locations: classpath:sqlmapper/**/*.xml
# mybatis.configuration.map-underscore-to-camel-case=true

... # End